apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - mysql-pvc.yaml
  - mysql.yaml
  - suma.yaml
  - resta.yaml
  - ecuacion.yaml
  - almacenar.yaml
  - ingress.yaml

images:
  - name: ${DOCKER_REGISTRY}/suma
    newName: luisdanielge/suma
    newTag: latest
  - name: ${DOCKER_REGISTRY}/resta
    newName: luisdanielge/resta
    newTag: latest
  - name: ${DOCKER_REGISTRY}/ecuacion
    newName: luisdanielge/ecuacion
    newTag: latest
  - name: ${DOCKER_REGISTRY}/almacenar
    newName: luisdanielge/almacenar
    newTag: latest